// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsYLxqjVhpZj6Zdf5P1CX2RbLTWdtxavA',
    appId: '1:139627910731:web:bec43256dd650a5020dfce',
    messagingSenderId: '139627910731',
    projectId: 'chat-5520f',
    authDomain: 'chat-5520f.firebaseapp.com',
    storageBucket: 'chat-5520f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbn1asiXs9MalZgRxICT1q7ZmZH5_n2yg',
    appId: '1:139627910731:android:4075acb95bb5469020dfce',
    messagingSenderId: '139627910731',
    projectId: 'chat-5520f',
    storageBucket: 'chat-5520f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZVcOGti-7BGvOXSDIBM8a_tu_7oBy0V0',
    appId: '1:139627910731:ios:64fcd5b3ea597fbb20dfce',
    messagingSenderId: '139627910731',
    projectId: 'chat-5520f',
    storageBucket: 'chat-5520f.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZVcOGti-7BGvOXSDIBM8a_tu_7oBy0V0',
    appId: '1:139627910731:ios:64fcd5b3ea597fbb20dfce',
    messagingSenderId: '139627910731',
    projectId: 'chat-5520f',
    storageBucket: 'chat-5520f.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsYLxqjVhpZj6Zdf5P1CX2RbLTWdtxavA',
    appId: '1:139627910731:web:aa5ac8eb8eb11ae920dfce',
    messagingSenderId: '139627910731',
    projectId: 'chat-5520f',
    authDomain: 'chat-5520f.firebaseapp.com',
    storageBucket: 'chat-5520f.appspot.com',
  );
}
